// src/shared/ui/Button/Button.vue
<script setup lang="ts">
import { computed } from 'vue';

import styles from './button.module.scss';
import type { ButtonVariant } from './button.types';

const props = withDefaults(
  defineProps<{
    variant?: ButtonVariant;
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
  }>(),
  {
    variant: 'primary',
    disabled: false,
    type: 'button',
  }
);

const classes = computed(() => ({
  [styles.button]: true,
  [styles[props.variant]]: true,
  [styles.disabled]: props.disabled,
}));

const particles = Array.from({ length: 30 });
</script>

<template>
  <button :class="classes" :disabled="disabled" :type="type">
    <slot />
    <span :class="styles.particles">
      <span v-for="(_, i) in particles" :key="i" :class="styles.particle" />
    </span>
  </button>
</template>

// src/shared/ui/Button/Button.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react';

import clsx from 'clsx';

import styles from './button.module.scss';

import { Typography } from '../Typography/Typography';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'gradient';
  // gradient?: boolean;
}
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ children, variant = 'primary', disabled, ...props }, ref) => {
    const particles = Array(30)
      .fill(0)
      .map((_, i) => <span key={i} className={styles.particle} />);

    return (
      <Typography
        ref={ref}
        variant="button"
        as="button"
        className={clsx(styles.button, {
          [`${styles[variant]}`]: variant,
          [`${styles.disabled}`]: disabled,
        })}
        {...props}
      >
        {children}
        <span className={styles.particles}>{particles}</span>
      </Typography>
    );
  }
);
